image: python:3.11

services:
  - postgres:17

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/test_db"
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip install pre-commit autoflake
    - pre-commit install
    - pre-commit run --all-files
    # Если есть изменения после форматирования, делаем коммит
    - |
      if [[ -n "$(git status --porcelain)" ]]; then
        git config --global user.email "gitlab-ci@example.com"
        git config --global user.name "GitLab CI"
        git add .
        git commit -m "style: auto-format code [skip ci]"
        git push "https://oauth2:${CI_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_COMMIT_REF_NAME}
      fi

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-cov pytest-asyncio psycopg2-binary
    - pytest -v --cov=app