image: python:3.11-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "test_user"
  POSTGRES_PASSWORD: "test_password"
  POSTGRES_HOST: "postgres"
  TEST_DATABASE_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB"

stages:
  - format
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - .pip-cache/
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - . venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

format:
  stage: format
  script:
    - pip install black
    - black app
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git add .
    - git commit -m "Apply black formatting" || echo "No changes to commit"
    - git push origin HEAD:$CI_COMMIT_REF_NAME || echo "No changes to push"

lint:
  stage: lint
  script:
    - pip install flake8
    - echo "Running flake8..."
    - flake8 app --config=setup.cfg

test:
  stage: test
  services:
    - postgres:13
  script:
    - pytest -v --cov=app

build:
  stage: build
  script:
    - docker build -t kyc-service .
  only:
    - main
    - develop

deploy:
  stage: deploy
  script:
    - echo "Deploy to production"
  only:
    - main
  when: manual 