image: python:3.11-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

stages:
  - lint
  - test
  - build

before_script:
  - python -V
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install flake8 black isort
    - flake8 app
    - black --check app
    - isort --check-only app

test:
  stage: test
  services:
    - postgres:13
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    POSTGRES_HOST: postgres
  script:
    - pytest app/tests -v --cov=app

build:
  stage: build
  script:
    - docker build -t kyc-service .
  only:
    - main
    - develop 