image: python:3.11

services:
  - postgres:17

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/test_db"
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - pip install pre-commit autoflake
    - pre-commit install
    - pre-commit run --all-files

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-cov pytest-asyncio psycopg2-binary
    - pytest -v --cov=app